### ISSUE TITLE
Reproducing results

### ISSUE THREAD

**Issue by cemysf** [mks0601/PedestrianDetection_FastFeaturePyramid#1]
Hello,

How can I reproduce results? I have altered files for linux compatibility, I can compile all main.cpp files. Also, I have the INRIA dataset for dataGen/main.cpp and I can extract randomly cropped negative examples.

However, I cannot use Boosted_tree/main.cpp or Random_forest/main.cpp. Both of them require some files, such as "pos_hog/%d.txt" and "neg_adaboost/%d.txt". 

How can I obtain or create these files?

**Comment by mks0601** [comment]
Hi
Since it is long time ago when i implemented this work, i cannot remember clearly.
As i remember, that txt files are hog features of positive image and negative image.

You can calculate the hog feature using OPENCV libray. I stored the features in order to shorten running time.

**Comment by cemysf** [comment]
Ok thank you for your help, I'll use another implementation
